export default [
	// ...other config
	{
		// Note: there should be no other properties in this object
		ignores: [
			'**/*.log',
			'**/.DS_Store',
			'*.',
			'.vscode/settings.json',
			'.history',
			'.yarn',
			'bazel-*',
			'bazel-bin',
			'bazel-out',
			'bazel-qwik',
			'bazel-testlogs',
			'dist',
			'dist-dev',
			'lib',
			'lib-types',
			'etc',
			'external',
			'node_modules',
			'temp',
			'tsc-out',
			'tsdoc-metadata.json',
			'target',
			'output',
			'rollup.config.js',
			'build',
			'.cache',
			'.vscode',
			'.rollup.cache',
			'tsconfig.tsbuildinfo',
			'vite.config.ts',
			'.eslintrc.cjs',
			'pnpm-lock.yaml',
			'package-lock.json',
			'yarn.lock',
			'server',
		],
	},
]
