[build]
publish = "dist"
command = "npm run test build"

[[edge_functions]]
path = "/*"
function = "entry.netlify-edge"
[dev]
framework = "#static"
[[headers]]
  for = "/assets/images/photography/black/*"
[headers.values]
  Cache-Control = "public, max-age=60"