[build]
publish = "dist"
command = "npm run build"

[[edge_functions]]
path = "/*"
function = "entry.netlify-edge"
[dev]
framework = "#static"
[[headers]]
  for = "/assets/images/photography/black/*"
[headers.values]
  Cache-Control = "public, max-age=60"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    preset = "desktop" # Optionally run Lighthouse using a desktop configuration